"""empty message

Revision ID: 35d70be91a9a
Revises: be9dabc13a02
Create Date: 2023-12-14 07:44:09.888762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d70be91a9a'
down_revision = 'be9dabc13a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.create_unique_constraint('_coach_email_uc', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint('_coach_email_uc', type_='unique')

    # ### end Alembic commands ###
